version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  deploy-job:
    docker:
      - image: governmentpaas/awscli
    working_directory: ~/repo
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync public s3://julien.codes/ --delete
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build-job
    - deploy-job:
        requires:
          - build-job
        filters:
          branches:
            only: master