version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
      - image: governmentpaas/awscli
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # build
      - run: yarn build
      # deploy
      - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            aws s3 sync ~/repo/public s3://julien.codes --delete
          fi

