version: 2.0

references:
  container_config: &container_config
    working_directory: /root/site

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build-job:
    <<: *container_config
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: *workspace_root
          paths: public

  deploy-job:
    <<: *container_config
    docker:
      - image: governmentpaas/awscli
    steps:
      - *attach_workspace
      - run:
          name: Deploy to S3
          command: aws s3 sync public s3://julien.codes/ --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build-job
    - deploy-job:
        requires:
          - build-job
        filters:
          branches:
            only: master